server:
  port: 8050
  additional-ports: 8051,8052

spring:
  datasource:
    url: jdbc:mysql://39.100.136.215:30100/isid
    username: master
    password: Kjmxwed@7789
    driver-class-name: com.mysql.cj.jdbc.Driver